### ISSUE TITLE
Recreate beast creation and attack choice screen

### ISSUE THREAD

**Issue by ChrisCanaday** [utk-cs340-fall22/BattleBeasts#66]

**Comment by ColinC5** [comment]
All of the logic for presenting the allowed modifiers and attacks is done and can be used for this redesign.
The new design should include little information boxes that can be scrolled through instead of dropdown boxes.
For example, an info box for an attack would include its name, type, damage per attack, and attack count. Having icons to label those fields could look nice.
For displaying these boxes, I was thinking we could maybe have buttons on the side or bottom of the screen to select what selection of boxes you want to scroll through, and those boxes would then appear in window that could be scrolled through. The selection boxes can be clicked on and then the button on the left would, for example, instead of saying "modifier" it would take on the appearance of the info box for the modifier that was just selected.
