### ISSUE TITLE
Beast creation doesn't reload moves

### ISSUE THREAD

**Issue by stephhill77** [utk-cs340-fall22/BattleBeasts#84]
If you change your beast during move selection, the moves don't reload until you re-select a modifier.

**Comment by ColinC5** [comment]
In order to for the player's options for attacks to be determined both the beast and modifier need to be chosen. How it is now doesn't break the game because if you change your beast then the modifier field gets reset, and if any of the fields are left in their default state then you cannot move on to the bracket.
This should be addressed though because it can be hard to notice that your modifier got reset.

**Comment by ChrisCanaday** [comment]
I can grab this during sprint 4
